# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Avoid.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Avoid(object):
    def setupUi(self, Avoid):
        Avoid.setObjectName(_fromUtf8("Avoid"))
        Avoid.resize(286, 348)
        Avoid.setMinimumSize(QtCore.QSize(286, 348))
        Avoid.setMaximumSize(QtCore.QSize(286, 348))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imageformats/smines_favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Avoid.setWindowIcon(icon)
        Avoid.setStyleSheet(_fromUtf8("QWidget{\n"
"    background-color: rgb(17, 17, 17); \n"
"    color:white;\n"
"    border: 0;\n"
"}\n"
"\n"
"#Done {\n"
"    color: white;\n"
"    background-color: purple; \n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"}"))
        self.pushButton_6 = QtGui.QPushButton(Avoid)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 90, 45, 45))
        self.pushButton_6.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("imageformats/tileNewBig.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_8 = QtGui.QPushButton(Avoid)
        self.pushButton_8.setGeometry(QtCore.QRect(120, 90, 45, 45))
        self.pushButton_8.setText(_fromUtf8(""))
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_17 = QtGui.QPushButton(Avoid)
        self.pushButton_17.setGeometry(QtCore.QRect(220, 190, 45, 45))
        self.pushButton_17.setText(_fromUtf8(""))
        self.pushButton_17.setIcon(icon1)
        self.pushButton_17.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_19 = QtGui.QPushButton(Avoid)
        self.pushButton_19.setGeometry(QtCore.QRect(170, 190, 45, 45))
        self.pushButton_19.setText(_fromUtf8(""))
        self.pushButton_19.setIcon(icon1)
        self.pushButton_19.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.pushButton_10 = QtGui.QPushButton(Avoid)
        self.pushButton_10.setGeometry(QtCore.QRect(70, 90, 45, 45))
        self.pushButton_10.setText(_fromUtf8(""))
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_23 = QtGui.QPushButton(Avoid)
        self.pushButton_23.setGeometry(QtCore.QRect(120, 240, 45, 45))
        self.pushButton_23.setText(_fromUtf8(""))
        self.pushButton_23.setIcon(icon1)
        self.pushButton_23.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.pushButton_12 = QtGui.QPushButton(Avoid)
        self.pushButton_12.setGeometry(QtCore.QRect(220, 140, 45, 45))
        self.pushButton_12.setText(_fromUtf8(""))
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_2 = QtGui.QPushButton(Avoid)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 40, 45, 45))
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_15 = QtGui.QPushButton(Avoid)
        self.pushButton_15.setGeometry(QtCore.QRect(70, 140, 45, 45))
        self.pushButton_15.setText(_fromUtf8(""))
        self.pushButton_15.setIcon(icon1)
        self.pushButton_15.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_13 = QtGui.QPushButton(Avoid)
        self.pushButton_13.setGeometry(QtCore.QRect(120, 140, 45, 45))
        self.pushButton_13.setText(_fromUtf8(""))
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_9 = QtGui.QPushButton(Avoid)
        self.pushButton_9.setGeometry(QtCore.QRect(170, 90, 45, 45))
        self.pushButton_9.setText(_fromUtf8(""))
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_22 = QtGui.QPushButton(Avoid)
        self.pushButton_22.setGeometry(QtCore.QRect(220, 240, 45, 45))
        self.pushButton_22.setText(_fromUtf8(""))
        self.pushButton_22.setIcon(icon1)
        self.pushButton_22.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_4 = QtGui.QPushButton(Avoid)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 40, 45, 45))
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_18 = QtGui.QPushButton(Avoid)
        self.pushButton_18.setGeometry(QtCore.QRect(120, 190, 45, 45))
        self.pushButton_18.setText(_fromUtf8(""))
        self.pushButton_18.setIcon(icon1)
        self.pushButton_18.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_24 = QtGui.QPushButton(Avoid)
        self.pushButton_24.setGeometry(QtCore.QRect(170, 240, 45, 45))
        self.pushButton_24.setText(_fromUtf8(""))
        self.pushButton_24.setIcon(icon1)
        self.pushButton_24.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(Avoid)
        self.pushButton_25.setGeometry(QtCore.QRect(70, 240, 45, 45))
        self.pushButton_25.setText(_fromUtf8(""))
        self.pushButton_25.setIcon(icon1)
        self.pushButton_25.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.label = QtGui.QLabel(Avoid)
        self.label.setGeometry(QtCore.QRect(50, 5, 180, 26))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("imageformats/smines.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_14 = QtGui.QPushButton(Avoid)
        self.pushButton_14.setGeometry(QtCore.QRect(170, 140, 45, 45))
        self.pushButton_14.setText(_fromUtf8(""))
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_7 = QtGui.QPushButton(Avoid)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 90, 45, 45))
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton = QtGui.QPushButton(Avoid)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 45, 45))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(45, 45))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_16 = QtGui.QPushButton(Avoid)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 190, 45, 45))
        self.pushButton_16.setText(_fromUtf8(""))
        self.pushButton_16.setIcon(icon1)
        self.pushButton_16.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.Done = QtGui.QPushButton(Avoid)
        self.Done.setGeometry(QtCore.QRect(108, 300, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.Done.setFont(font)
        self.Done.setStyleSheet(_fromUtf8(""))
        self.Done.setObjectName(_fromUtf8("Done"))
        self.pushButton_20 = QtGui.QPushButton(Avoid)
        self.pushButton_20.setGeometry(QtCore.QRect(70, 190, 45, 45))
        self.pushButton_20.setText(_fromUtf8(""))
        self.pushButton_20.setIcon(icon1)
        self.pushButton_20.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_5 = QtGui.QPushButton(Avoid)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 40, 45, 45))
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_3 = QtGui.QPushButton(Avoid)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 40, 45, 45))
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_21 = QtGui.QPushButton(Avoid)
        self.pushButton_21.setGeometry(QtCore.QRect(20, 240, 45, 45))
        self.pushButton_21.setText(_fromUtf8(""))
        self.pushButton_21.setIcon(icon1)
        self.pushButton_21.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_11 = QtGui.QPushButton(Avoid)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 140, 45, 45))
        self.pushButton_11.setText(_fromUtf8(""))
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))

        self.retranslateUi(Avoid)
        QtCore.QMetaObject.connectSlotsByName(Avoid)

    def retranslateUi(self, Avoid):
        Avoid.setWindowTitle(_translate("Avoid", "Avoid Tiles", None))
        self.Done.setToolTip(_translate("Avoid", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:400;\">Starts the Bot</span></p></body></html>", None))
        self.Done.setText(_translate("Avoid", "Done", None))

class AvoidForm(QtGui.QWidget):
    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        self.ui = Ui_Avoid()
        self.ui.setupUi(self)