# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OddsApp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OddsApp(object):
    def setupUi(self, OddsApp):
        OddsApp.setObjectName(_fromUtf8("OddsApp"))
        OddsApp.resize(400, 348)
        OddsApp.setMinimumSize(QtCore.QSize(400, 348))
        OddsApp.setMaximumSize(QtCore.QSize(400, 348))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imageformats/smines_favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OddsApp.setWindowIcon(icon)
        OddsApp.setStyleSheet(_fromUtf8("QWidget{\n"
"    background-color: rgb(17, 17, 17); \n"
"    color:white;\n"
"    border: 0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"     border: 0;\n"
"     background: #222222;\n"
"    width:0px;\n"
"    height:20px;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 0px;\n"
"}"))
        self.tableWidget = QtGui.QTableWidget(OddsApp)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 40, 406, 301))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(65)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(41, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(42, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(43, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(44, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(45, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(46, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(47, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(48, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(49, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(50, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(51, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(52, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(53, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(54, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(55, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(56, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(57, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(58, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(59, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(60, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(61, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(62, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(63, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(64, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(10, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(10, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(11, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(11, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(12, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(12, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(13, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(13, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(13, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(14, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(14, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(14, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(15, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(15, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(15, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(16, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(16, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(16, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(17, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(17, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(17, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(18, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(18, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(18, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(19, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(19, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(19, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(20, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(20, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(20, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(21, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(21, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(21, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(22, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(22, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(22, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(23, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(23, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(23, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(24, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(24, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(24, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(24, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(25, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(25, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(25, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(26, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(26, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(26, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(27, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(27, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(27, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(28, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(28, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(28, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(29, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(29, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(29, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(30, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(30, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(30, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(31, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(31, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(31, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(32, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(32, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(32, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(33, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(33, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(33, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(34, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(34, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(34, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(35, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(35, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(35, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(36, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(36, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(36, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(37, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(37, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(37, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(38, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(38, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(38, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(39, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(39, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(39, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(40, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(40, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(40, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(41, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(41, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(41, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(42, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(42, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(42, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(43, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(43, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(43, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(44, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(44, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(44, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(45, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(45, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(45, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(45, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setItem(46, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(46, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(46, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(46, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(47, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(47, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(47, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(48, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(48, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(48, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(49, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(49, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(49, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(50, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(50, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(50, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(51, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(51, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(51, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(52, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(52, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(52, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(53, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(53, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(53, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(54, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(54, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(54, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(55, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(55, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(55, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(56, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(56, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(56, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(57, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(57, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(57, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(58, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(58, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(58, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(59, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(59, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(59, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(60, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(60, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(60, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(61, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(61, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(61, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(62, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(62, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(62, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(63, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(63, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(63, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(64, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(64, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(64, 3, item)
        self.label = QtGui.QLabel(OddsApp)
        self.label.setGeometry(QtCore.QRect(110, 5, 180, 26))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("imageformats/smines.png")))
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(OddsApp)
        QtCore.QMetaObject.connectSlotsByName(OddsApp)

    def retranslateUi(self, OddsApp):
        OddsApp.setWindowTitle(_translate("OddsApp", "Odds", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("OddsApp", " ", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("OddsApp", "Mines", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("OddsApp", "Guesses", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("OddsApp", "Profit", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("OddsApp", "Chance", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("OddsApp", "1", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("OddsApp", "1", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("OddsApp", "3.999%", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("OddsApp", "96.000%", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("OddsApp", "2", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("OddsApp", "8.339%", None))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("OddsApp", "88.320%", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("OddsApp", "3", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("OddsApp", "13.066%", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("OddsApp", "77.722%", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("OddsApp", "4", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("OddsApp", "18.234%", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("OddsApp", "65.286%", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("OddsApp", "5", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("OddsApp", "23.909%", None))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("OddsApp", "52.229%", None))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("OddsApp", "6", None))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("OddsApp", "30.169%", None))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("OddsApp", "39.69%", None))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("OddsApp", "7", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("OddsApp", "37.111%", None))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("OddsApp", "28.58%", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("OddsApp", "8", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("OddsApp", "44.853%", None))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("OddsApp", "19.43%", None))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("OddsApp", "9", None))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("OddsApp", "53.544%", None))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("OddsApp", "12.44%", None))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("OddsApp", "10", None))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("OddsApp", "63.370%", None))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("OddsApp", "7.4627%", None))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("OddsApp", "11", None))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("OddsApp", "74.572%", None))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("OddsApp", "4.1791%", None))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("OddsApp", "12", None))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("OddsApp", "84.760%", None))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("OddsApp", "2.1731%", None))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("OddsApp", "13", None))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("OddsApp", "102.460%", None))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("OddsApp", "1.0431%", None))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("OddsApp", "14", None))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("OddsApp", "120.130%", None))
        item = self.tableWidget.item(13, 3)
        item.setText(_translate("OddsApp", "0.45897%", None))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("OddsApp", "15", None))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("OddsApp", "141.260%", None))
        item = self.tableWidget.item(14, 3)
        item.setText(_translate("OddsApp", "0.18359%", None))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("OddsApp", "16", None))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("OddsApp", "166.995%", None))
        item = self.tableWidget.item(15, 3)
        item.setText(_translate("OddsApp", "0.06609%", None))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("OddsApp", "17", None))
        item = self.tableWidget.item(16, 2)
        item.setText(_translate("OddsApp", "199.034%", None))
        item = self.tableWidget.item(16, 3)
        item.setText(_translate("OddsApp", "0.02115%", None))
        item = self.tableWidget.item(17, 1)
        item.setText(_translate("OddsApp", "18", None))
        item = self.tableWidget.item(17, 2)
        item.setText(_translate("OddsApp", "240.044%", None))
        item = self.tableWidget.item(17, 3)
        item.setText(_translate("OddsApp", "0.005922%", None))
        item = self.tableWidget.item(18, 1)
        item.setText(_translate("OddsApp", "19", None))
        item = self.tableWidget.item(18, 2)
        item.setText(_translate("OddsApp", "294.451%", None))
        item = self.tableWidget.item(18, 3)
        item.setText(_translate("OddsApp", "0.001421%", None))
        item = self.tableWidget.item(19, 1)
        item.setText(_translate("OddsApp", "20", None))
        item = self.tableWidget.item(19, 2)
        item.setText(_translate("OddsApp", "370.185%", None))
        item = self.tableWidget.item(19, 3)
        item.setText(_translate("OddsApp", "0.000284%", None))
        item = self.tableWidget.item(20, 1)
        item.setText(_translate("OddsApp", "21", None))
        item = self.tableWidget.item(20, 2)
        item.setText(_translate("OddsApp", "478.640%", None))
        item = self.tableWidget.item(20, 3)
        item.setText(_translate("OddsApp", "0.000045479%", None))
        item = self.tableWidget.item(21, 1)
        item.setText(_translate("OddsApp", "22", None))
        item = self.tableWidget.item(21, 2)
        item.setText(_translate("OddsApp", "663.800%", None))
        item = self.tableWidget.item(21, 3)
        item.setText(_translate("OddsApp", "0.000005458%", None))
        item = self.tableWidget.item(22, 1)
        item.setText(_translate("OddsApp", "23", None))
        item = self.tableWidget.item(22, 2)
        item.setText(_translate("OddsApp", "1038.410%", None))
        item = self.tableWidget.item(22, 3)
        item.setText(_translate("OddsApp", "0.000000437%", None))
        item = self.tableWidget.item(23, 1)
        item.setText(_translate("OddsApp", "24", None))
        item = self.tableWidget.item(23, 2)
        item.setText(_translate("OddsApp", "2131.280%", None))
        item = self.tableWidget.item(23, 3)
        item.setText(_translate("OddsApp", "0.000000017%", None))
        item = self.tableWidget.item(24, 0)
        item.setText(_translate("OddsApp", "3", None))
        item = self.tableWidget.item(24, 1)
        item.setText(_translate("OddsApp", "1", None))
        item = self.tableWidget.item(24, 2)
        item.setText(_translate("OddsApp", "13.090%", None))
        item = self.tableWidget.item(24, 3)
        item.setText(_translate("OddsApp", "88.000%", None))
        item = self.tableWidget.item(25, 1)
        item.setText(_translate("OddsApp", "2", None))
        item = self.tableWidget.item(25, 2)
        item.setText(_translate("OddsApp", "28.599%", None))
        item = self.tableWidget.item(25, 3)
        item.setText(_translate("OddsApp", "73.920%", None))
        item = self.tableWidget.item(26, 1)
        item.setText(_translate("OddsApp", "3", None))
        item = self.tableWidget.item(26, 2)
        item.setText(_translate("OddsApp", "47.117%", None))
        item = self.tableWidget.item(26, 3)
        item.setText(_translate("OddsApp", "59.136%", None))
        item = self.tableWidget.item(27, 1)
        item.setText(_translate("OddsApp", "4", None))
        item = self.tableWidget.item(27, 2)
        item.setText(_translate("OddsApp", "69.416%", None))
        item = self.tableWidget.item(27, 3)
        item.setText(_translate("OddsApp", "44.943%", None))
        item = self.tableWidget.item(28, 1)
        item.setText(_translate("OddsApp", "5", None))
        item = self.tableWidget.item(28, 2)
        item.setText(_translate("OddsApp", "96.522%", None))
        item = self.tableWidget.item(28, 3)
        item.setText(_translate("OddsApp", "32.359%", None))
        item = self.tableWidget.item(29, 1)
        item.setText(_translate("OddsApp", "6", None))
        item = self.tableWidget.item(29, 2)
        item.setText(_translate("OddsApp", "128.280%", None))
        item = self.tableWidget.item(29, 3)
        item.setText(_translate("OddsApp", "22.004%", None))
        item = self.tableWidget.item(30, 1)
        item.setText(_translate("OddsApp", "7", None))
        item = self.tableWidget.item(30, 2)
        item.setText(_translate("OddsApp", "169.150%", None))
        item = self.tableWidget.item(30, 3)
        item.setText(_translate("OddsApp", "14.083%", None))
        item = self.tableWidget.item(31, 1)
        item.setText(_translate("OddsApp", "8", None))
        item = self.tableWidget.item(31, 2)
        item.setText(_translate("OddsApp", "220.820%", None))
        item = self.tableWidget.item(31, 3)
        item.setText(_translate("OddsApp", "8.450%", None))
        item = self.tableWidget.item(32, 1)
        item.setText(_translate("OddsApp", "9", None))
        item = self.tableWidget.item(32, 2)
        item.setText(_translate("OddsApp", "286.630%", None))
        item = self.tableWidget.item(32, 3)
        item.setText(_translate("OddsApp", "4.732%", None))
        item = self.tableWidget.item(33, 1)
        item.setText(_translate("OddsApp", "10", None))
        item = self.tableWidget.item(33, 2)
        item.setText(_translate("OddsApp", "372.240%", None))
        item = self.tableWidget.item(33, 3)
        item.setText(_translate("OddsApp", "2.461%", None))
        item = self.tableWidget.item(34, 1)
        item.setText(_translate("OddsApp", "11", None))
        item = self.tableWidget.item(34, 2)
        item.setText(_translate("OddsApp", "485.350%", None))
        item = self.tableWidget.item(34, 3)
        item.setText(_translate("OddsApp", "1.181%", None))
        item = self.tableWidget.item(35, 1)
        item.setText(_translate("OddsApp", "12", None))
        item = self.tableWidget.item(35, 2)
        item.setText(_translate("OddsApp", "638.560%", None))
        item = self.tableWidget.item(35, 3)
        item.setText(_translate("OddsApp", "0.520%", None))
        item = self.tableWidget.item(36, 1)
        item.setText(_translate("OddsApp", "13", None))
        item = self.tableWidget.item(36, 2)
        item.setText(_translate("OddsApp", "851.160%", None))
        item = self.tableWidget.item(36, 3)
        item.setText(_translate("OddsApp", "0.208%", None))
        item = self.tableWidget.item(37, 1)
        item.setText(_translate("OddsApp", "14", None))
        item = self.tableWidget.item(37, 2)
        item.setText(_translate("OddsApp", "1155.530%", None))
        item = self.tableWidget.item(37, 3)
        item.setText(_translate("OddsApp", "0.075%", None))
        item = self.tableWidget.item(38, 1)
        item.setText(_translate("OddsApp", "15", None))
        item = self.tableWidget.item(38, 2)
        item.setText(_translate("OddsApp", "1622.390%", None))
        item = self.tableWidget.item(38, 3)
        item.setText(_translate("OddsApp", "0.024%", None))
        item = self.tableWidget.item(39, 1)
        item.setText(_translate("OddsApp", "16", None))
        item = self.tableWidget.item(39, 2)
        item.setText(_translate("OddsApp", "2277.872%", None))
        item = self.tableWidget.item(39, 3)
        item.setText(_translate("OddsApp", "0.007%", None))
        item = self.tableWidget.item(40, 1)
        item.setText(_translate("OddsApp", "17", None))
        item = self.tableWidget.item(40, 2)
        item.setText(_translate("OddsApp", "3198.183%", None))
        item = self.tableWidget.item(40, 3)
        item.setText(_translate("OddsApp", "0.002%", None))
        item = self.tableWidget.item(41, 1)
        item.setText(_translate("OddsApp", "18", None))
        item = self.tableWidget.item(41, 2)
        item.setText(_translate("OddsApp", "4490.321%", None))
        item = self.tableWidget.item(41, 3)
        item.setText(_translate("OddsApp", "0.000%", None))
        item = self.tableWidget.item(42, 1)
        item.setText(_translate("OddsApp", "19", None))
        item = self.tableWidget.item(42, 2)
        item.setText(_translate("OddsApp", "6304.511%", None))
        item = self.tableWidget.item(42, 3)
        item.setText(_translate("OddsApp", "0.000%", None))
        item = self.tableWidget.item(43, 1)
        item.setText(_translate("OddsApp", "20", None))
        item = self.tableWidget.item(43, 2)
        item.setText(_translate("OddsApp", "8851.675%", None))
        item = self.tableWidget.item(43, 3)
        item.setText(_translate("OddsApp", "0.000%", None))
        item = self.tableWidget.item(44, 1)
        item.setText(_translate("OddsApp", "21", None))
        item = self.tableWidget.item(44, 2)
        item.setText(_translate("OddsApp", "12427.949%", None))
        item = self.tableWidget.item(44, 3)
        item.setText(_translate("OddsApp", "0.000%", None))
        item = self.tableWidget.item(45, 1)
        item.setText(_translate("OddsApp", "22", None))
        item = self.tableWidget.item(45, 2)
        item.setText(_translate("OddsApp", "17449.119%", None))
        item = self.tableWidget.item(45, 3)
        item.setText(_translate("OddsApp", "0.000%", None))
        item = self.tableWidget.item(46, 0)
        item.setText(_translate("OddsApp", "5", None))
        item = self.tableWidget.item(46, 1)
        item.setText(_translate("OddsApp", "1", None))
        item = self.tableWidget.item(46, 2)
        item.setText(_translate("OddsApp", "24.000%", None))
        item = self.tableWidget.item(46, 3)
        item.setText(_translate("OddsApp", "80%", None))
        item = self.tableWidget.item(47, 1)
        item.setText(_translate("OddsApp", "2", None))
        item = self.tableWidget.item(47, 2)
        item.setText(_translate("OddsApp", "55.326%", None))
        item = self.tableWidget.item(47, 3)
        item.setText(_translate("OddsApp", "60.8%", None))
        item = self.tableWidget.item(48, 1)
        item.setText(_translate("OddsApp", "3", None))
        item = self.tableWidget.item(48, 2)
        item.setText(_translate("OddsApp", "96.746%", None))
        item = self.tableWidget.item(48, 3)
        item.setText(_translate("OddsApp", "43.776%", None))
        item = self.tableWidget.item(49, 1)
        item.setText(_translate("OddsApp", "4", None))
        item = self.tableWidget.item(49, 2)
        item.setText(_translate("OddsApp", "152.30%", None))
        item = self.tableWidget.item(49, 3)
        item.setText(_translate("OddsApp", "29.768%", None))
        item = self.tableWidget.item(50, 1)
        item.setText(_translate("OddsApp", "5", None))
        item = self.tableWidget.item(50, 2)
        item.setText(_translate("OddsApp", "227.99%", None))
        item = self.tableWidget.item(50, 3)
        item.setText(_translate("OddsApp", "19.051%", None))
        item = self.tableWidget.item(51, 1)
        item.setText(_translate("OddsApp", "6", None))
        item = self.tableWidget.item(51, 2)
        item.setText(_translate("OddsApp", "332.89%", None))
        item = self.tableWidget.item(51, 3)
        item.setText(_translate("OddsApp", "11.431%", None))
        item = self.tableWidget.item(52, 1)
        item.setText(_translate("OddsApp", "7", None))
        item = self.tableWidget.item(52, 2)
        item.setText(_translate("OddsApp", "481.38%", None))
        item = self.tableWidget.item(52, 3)
        item.setText(_translate("OddsApp", "6.4012%", None))
        item = self.tableWidget.item(53, 1)
        item.setText(_translate("OddsApp", "8", None))
        item = self.tableWidget.item(53, 2)
        item.setText(_translate("OddsApp", "696.04%", None))
        item = self.tableWidget.item(53, 3)
        item.setText(_translate("OddsApp", "3.3286%", None))
        item = self.tableWidget.item(54, 1)
        item.setText(_translate("OddsApp", "9", None))
        item = self.tableWidget.item(54, 2)
        item.setText(_translate("OddsApp", "1014.45%", None))
        item = self.tableWidget.item(54, 3)
        item.setText(_translate("OddsApp", "1.5977%", None))
        item = self.tableWidget.item(55, 1)
        item.setText(_translate("OddsApp", "10", None))
        item = self.tableWidget.item(55, 2)
        item.setText(_translate("OddsApp", "1600.5%", None))
        item = self.tableWidget.item(55, 3)
        item.setText(_translate("OddsApp", "0.70301%", None))
        item = self.tableWidget.item(56, 1)
        item.setText(_translate("OddsApp", "11", None))
        item = self.tableWidget.item(56, 2)
        item.setText(_translate("OddsApp", "2268.8%", None))
        item = self.tableWidget.item(56, 3)
        item.setText(_translate("OddsApp", "0.281204%", None))
        item = self.tableWidget.item(57, 1)
        item.setText(_translate("OddsApp", "12", None))
        item = self.tableWidget.item(57, 2)
        item.setText(_translate("OddsApp", "3532.7%", None))
        item = self.tableWidget.item(57, 3)
        item.setText(_translate("OddsApp", "0.101233%", None))
        item = self.tableWidget.item(58, 1)
        item.setText(_translate("OddsApp", "13", None))
        item = self.tableWidget.item(58, 2)
        item.setText(_translate("OddsApp", "5712.3%", None))
        item = self.tableWidget.item(58, 3)
        item.setText(_translate("OddsApp", "0.0323947%", None))
        item = self.tableWidget.item(59, 1)
        item.setText(_translate("OddsApp", "14", None))
        item = self.tableWidget.item(59, 2)
        item.setText(_translate("OddsApp", "9697.8%", None))
        item = self.tableWidget.item(59, 3)
        item.setText(_translate("OddsApp", "0.00907052%", None))
        item = self.tableWidget.item(60, 1)
        item.setText(_translate("OddsApp", "15", None))
        item = self.tableWidget.item(60, 2)
        item.setText(_translate("OddsApp", "17533%", None))
        item = self.tableWidget.item(60, 3)
        item.setText(_translate("OddsApp", "0.00217692%", None))
        item = self.tableWidget.item(61, 1)
        item.setText(_translate("OddsApp", "16", None))
        item = self.tableWidget.item(61, 2)
        item.setText(_translate("OddsApp", "34462%", None))
        item = self.tableWidget.item(61, 3)
        item.setText(_translate("OddsApp", "0.00043538%", None))
        item = self.tableWidget.item(62, 1)
        item.setText(_translate("OddsApp", "17", None))
        item = self.tableWidget.item(62, 2)
        item.setText(_translate("OddsApp", "75936%", None))
        item = self.tableWidget.item(62, 3)
        item.setText(_translate("OddsApp", "0.00006966%", None))
        item = self.tableWidget.item(63, 1)
        item.setText(_translate("OddsApp", "18", None))
        item = self.tableWidget.item(63, 2)
        item.setText(_translate("OddsApp", "197593%", None))
        item = self.tableWidget.item(63, 3)
        item.setText(_translate("OddsApp", "0.00000836%", None))
        item = self.tableWidget.item(64, 1)
        item.setText(_translate("OddsApp", "19", None))
        item = self.tableWidget.item(64, 2)
        item.setText(_translate("OddsApp", "672055%", None))
        item = self.tableWidget.item(64, 3)
        item.setText(_translate("OddsApp", "0.00000067%", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

class OddsForm(QtGui.QWidget):
    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        self.ui = Ui_OddsApp()
        self.ui.setupUi(self)